accueil_home:
    path: /
    defaults: { _controller: MacroBundle:Nutriments:index }

macro_home:
    path: /nutriments
    defaults: { _controller: MacroBundle:Nutriments:nutriments }

macro_calculatrice:
    path: /calculatrice
    defaults: { _controller: MacroBundle:Nutriments:calculatrice }
